-- ==============================================================================
-- TÍNH NĂNG: LƯU VẾT VÀ HIỂN THỊ ẢNH XEM NHIỀU NHẤT TRONG 24 GIỜ QUA (TRENDING 24H)
-- ==============================================================================

-- 1. Tạo bảng lưu vết từng lượt xem ảnh
CREATE TABLE IF NOT EXISTS public.photo_views_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL REFERENCES public.photos(id) ON DELETE CASCADE,
    viewer_id UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Tạo chỉ mục (index) để truy vấn thống kê lượt xem trong 24h qua cực nhanh
CREATE INDEX IF NOT EXISTS idx_photo_views_log_photo_created
ON public.photo_views_log (photo_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_photo_views_log_created_at
ON public.photo_views_log (created_at DESC);

-- 3. Bật bảo mật mức dòng (Row Level Security - RLS)
ALTER TABLE public.photo_views_log ENABLE ROW LEVEL SECURITY;

-- Chính sách: Cho phép tất cả người dùng (kể cả khách chưa đăng nhập) ghi log lượt xem
DROP POLICY IF EXISTS "Cho phép tất cả ghi log lượt xem" ON public.photo_views_log;
CREATE POLICY "Cho phép tất cả ghi log lượt xem"
ON public.photo_views_log FOR INSERT
WITH CHECK (true);

-- Chính sách: Cho phép đọc log để thống kê
DROP POLICY IF EXISTS "Cho phép tất cả đọc log lượt xem" ON public.photo_views_log;
CREATE POLICY "Cho phép tất cả đọc log lượt xem"
ON public.photo_views_log FOR SELECT
USING (true);

-- 4. Tạo hàm RPC lấy Top 5 ảnh được xem nhiều nhất trong 24 giờ qua
-- Có hỗ trợ bộ lọc (both / bus / coach) và fallback tự động theo lượt xem tổng nếu chưa có đủ log 24h
CREATE OR REPLACE FUNCTION public.get_trending_photos_24h(
    filter_type text DEFAULT 'both',
    limit_num int DEFAULT 5
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    result jsonb;
BEGIN
    SELECT jsonb_agg(row_to_json(t))
    INTO result
    FROM (
        SELECT 
            p.*,
            COALESCE(v24.cnt, 0) AS views_24h,
            jsonb_build_object(
                'id', pr.id,
                'username', pr.username,
                'role', pr.role,
                'subroles', pr.subroles,
                'ban_status', pr.ban_status
            ) AS profiles,
            jsonb_build_object(
                'model', v.model
            ) AS vehicles
        FROM public.photos p
        LEFT JOIN (
            SELECT photo_id, COUNT(*) AS cnt
            FROM public.photo_views_log
            WHERE created_at >= NOW() - INTERVAL '24 hours'
            GROUP BY photo_id
        ) v24 ON p.id = v24.photo_id
        LEFT JOIN public.profiles pr ON p.uploader_id = pr.id
        LEFT JOIN public.vehicles v ON p.license_plate = v.license_plate
        WHERE p.status = 'approved'
          AND (filter_type = 'both' OR p.type = filter_type)
        ORDER BY COALESCE(v24.cnt, 0) DESC, p.views DESC, p.created_at DESC
        LIMIT limit_num
    ) t;

    RETURN COALESCE(result, '[]'::jsonb);
END;
$$;
