-- ==============================================================================
-- TÍNH NĂNG: LƯU VẾT VÀ HIỂN THỊ ẢNH XEM NHIỀU NHẤT TRONG 24 GIỜ QUA (TRENDING 24H)
-- PHIÊN BẢN: PRODUCTION READY (TỐI ƯU BẢO MẬT & HIỆU NĂNG)
-- ==============================================================================

-- 1. Tạo bảng lưu vết từng lượt xem ảnh
CREATE TABLE IF NOT EXISTS public.photo_views_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL REFERENCES public.photos(id) ON DELETE CASCADE,
    viewer_id UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Tạo chỉ mục tối ưu cho truy vấn quét theo thời gian (Time-range scanning)
CREATE INDEX IF NOT EXISTS idx_photo_views_log_photo_created
ON public.photo_views_log (photo_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_photo_views_log_created_at
ON public.photo_views_log (created_at DESC);

-- 3. Cấu hình bảo mật mức dòng (RLS)
ALTER TABLE public.photo_views_log ENABLE ROW LEVEL SECURITY;

-- Chính sách INSERT: Cho phép tất cả mọi người (kể cả Guest) ghi log lượt xem
DROP POLICY IF EXISTS "Cho phép tất cả ghi log lượt xem" ON public.photo_views_log;
CREATE POLICY "Cho phép tất cả ghi log lượt xem"
ON public.photo_views_log FOR INSERT
WITH CHECK (true);

-- LƯU Ý PRODUCTION: ĐÃ XÓA CHÍNH SÁCH SELECT. 
-- Bảng log chứa thông tin riêng tư (ai xem gì lúc nào), chỉ cho phép hàm RPC chạy với quyền SECURITY DEFINER đọc.

-- 4. Tạo hàm RPC lấy Top ảnh trending trong 24 giờ qua
CREATE OR REPLACE FUNCTION public.get_trending_photos_24h(
    filter_type TEXT DEFAULT 'both',
    limit_num INT DEFAULT 5
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER -- Chạy với quyền Admin để bypass RLS nội bộ, tăng tốc JOIN
AS $$
DECLARE
    result JSONB;
BEGIN
    -- Kiểm tra điều kiện đầu vào để bảo vệ tài nguyên database
    IF limit_num <= 0 OR limit_num > 50 THEN
        limit_num := 5;
    END IF;

    IF filter_type NOT IN ('both', 'bus', 'coach') THEN
        filter_type := 'both';
    END IF;

    SELECT jsonb_agg(row_to_json(t))
    INTO result
    FROM (
        SELECT 
            p.id,
            p.url,
            p.license_plate,
            p.uploader_id,
            p.views,
            p.views AS total_views,
            p.location,
            p.province,
            p.route_no,
            p.operator,
            p.type,
            p.taken_at,
            p.created_at,
            COALESCE(v24.cnt, 0) AS views_24h,
            
            jsonb_build_object(
                'id', pr.id,
                'username', pr.username,
                'role', pr.role,
                'subroles', pr.subroles,
                'avatar_url', pr.avatar_url,
                'ban_status', pr.ban_status
            ) AS profiles,
            
            jsonb_build_object(
                'model', v.model
            ) AS vehicles
        FROM public.photos p
        
        LEFT JOIN (
            SELECT photo_id, COUNT(*) AS cnt
            FROM public.photo_views_log
            WHERE created_at >= (NOW() - INTERVAL '24 hours')
            GROUP BY photo_id
        ) v24 ON p.id = v24.photo_id
        
        LEFT JOIN public.profiles pr ON p.uploader_id = pr.id
        LEFT JOIN public.vehicles v ON p.license_plate = v.license_plate
        
        WHERE p.status = 'approved'
          AND (filter_type = 'both' OR p.type = filter_type)
          
        ORDER BY COALESCE(v24.cnt, 0) DESC, p.views DESC, p.created_at DESC
        LIMIT limit_num
    ) t;

    RETURN COALESCE(result, '[]'::jsonb);
END;
$$;
